[package]
name = "panopticon"
version = "0.1.0"
authors = ["Andreas Ots <qrpth@qrpth.eu>"]

[dependencies]
elastic_reqwest = "0.20.9"
gotham = "0.2.0"
gotham_derive = "0.2.0"
json_str = "0.5.1"
reqwest = "0.8.5"
